function.exe:function_imp.o function_app.o
	c++ function_imp.o function_app.o -o fuction.exe
function_imp.o:function_imp.cpp
	c++ -c function_imp.cpp
function_app.o:function_app.cpp
	c++ -c function_app.cpp
