main.exe:cStackLList.o cStackLListImp.o
	c++ -o main.exe cStackLList.o cStackLListImp.o
cStackLList.o:cStackLList.cpp
	c++ -c cStackLList.cpp
cStackLListImp.o:cStackLListImp.cpp
	c++ -c cStackLListImp.cpp
